apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

vpc:
  id: "vpc-09dadd9e423c04f91"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1b: { id: subnet-096b78110a39a544e }
      us-east-1f: { id: subnet-01483b41d7300ff42 }
      us-east-1c: { id: subnet-0875226995de36cf2 }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 4
    ssh: 
      allow: true
      publicKeyName: k8s-keypair
    tags:
      Name: ng-db
  - name: ng-spot
    instanceType: t3.small
    labels: { role: builders }
    minSize: 1
    maxSize: 2
    spot: true
    ssh: 
      allow: true
      publicKeyName: k8s-keypair
    tags:
      Name: ng-spot
