kind: Pod
apiVersion: v1
metadata:
  name: firstpod
  labels: 
    app: fp
    release: stable
    team: devops
  annotations:
    logDir: "/var/log"
spec:
  containers:
    - name: db
      image: redis
    - name: web
      image: httpd
    - name: nginx
      image: nginx
